---
- name: Maintain all edge devices
  hosts: all
  remote_user: debian
  tasks:
#############################################################################################
#
# configure /etc/network/interfaces.d files
#
##############################################################################################

  - name: Configure WAN port
    ansible.builtin.template:
      src: ./eth0.j2
      dest: /etc/network/interfaces.d/eth0

  - name: Configure LAN port
    ansible.builtin.template:
      src: ./eth1.j2
      dest: /etc/network/interfaces.d/eth1


###############################################################################################
#
#  IP tables setup
#
###############################################################################################

  - name: "flush all iptables rules"
    ansible.builtin.iptables:
      table: nat
      flush: yes


  - name: enable IP Forwarding in the kernel if needed
    ansible.posix.sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
    when: iplist is defined

  - name: build PREROUTING rules from list
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      destination: "{{ item.external }}"
      jump: DNAT
      to_destination: "{{ item.internal }}"
    with_items: "{{ iplist }}"
    when: iplist is defined
    notify:
      - Restart networking
      - saveiptables

  - name: build POSTROUTING rules from list
    ansible.builtin.iptables:
      table: nat
      chain: POSTROUTING
      destination: "{{ item.internal }}"
      jump: SNAT
      to_source: "{{ lanIP }}"
    with_items: "{{ iplist }}"
    when: iplist is defined
    notify:
      - Restart networking
      - saveiptables

#################################################################################################
#
# Date time and timezone
#
#################################################################################################

  - name: remove old ntp  
    ansible.builtin.apt:
      name: ntp
      state: absent

  - name: add ntp server to config
    ansible.builtin.shell:
      cmd: sed -i '/#NTP=/c\NTP=10.4.1.200' /etc/systemd/timesyncd.conf

  - name: ensure systemd-timesyncd is enabled and started
    ansible.builtin.systemd:
      name: systemd-timesyncd
      state: started
      enabled: yes
      daemon_reload: yes

  - name: set timezone to America/Toronto
    timezone:
      name: America/Toronto



#################################################################################################
#
#  Reboot the unit every sunday morning at 4am
#
#################################################################################################

  - name: Reboot Sundays at 4AM
    ansible.builtin.cron:
      name: "system reboot"
      minute: "0"
      hour: "4"
      weekday: 0
      job: "sudo reboot now"


#################################################################################################
#
#  handlers
#
#################################################################################################

  handlers:

    - name: saveiptables
      shell: iptables-save > /etc/iptables/rules.v4

# this must run last: a new setup changes the ip address of the wan interface
    - name: Restart networking
      ansible.builtin.service:
        name: networking
        state: restarted
