---
- name: Maintain machines on the floor
  hosts: test
  remote_user: root
  

  tasks:
  - name: Update repositories cache and perform a safe upgrade
    apt:
      update_cache: yes
#      upgrade: safe

  - name: Clean up apt
    apt:
      autoclean: yes
      autoremove: yes

  - name: Install packages
    apt:
      pkg:
       - nano
       - ufw
      update_cache: yes

###############################################################################################
#
# configure /etc/network/interfaces.d files
#
##############################################################################################




###############################################################################################
#  
#  IP tables setup
#
###############################################################################################

  - name: "flush all iptables rules"
    iptables:
      flush: yes

#  Setup iptables with loop

#   debug:
#     msg: "{{ item.internal }}:{{ item.external }}"
#   with_items: "{{ iplist }}"

  - name: build PREROUTING rules from list 
    ansible.builtin.iptables:
      table: nat
      chain: PREROUTING
      destination: "{{ item.external }}"
      jump: DNAT
      to_destination: "{{ item.internal }}" 
    with_items: "{{ iplist }}"

  - name: build POSTROUTING rules from list 
    ansible.builtin.iptables:
      table: nat
      chain: POSTROUTING
      destination: "{{ item.internal }}"
      jump: SNAT
      to_source: "{{ item.external }}"
    with_items: "{{ iplist }}"
