ungrouped:
  hosts:
    new108:  # 
      ansible_host: '10.4.45.108'
      wanIP: '10.4.45.108'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main PLC
          external: '10.4.43.6'

      # prodmon:
      #   collect_config: ' collect.yml'
      #   post_config: 'post.yml'

    10R140Laser_1725:  # 
      ansible_host: '10.4.45.108'
      wanIP: '10.4.44.108'
      lanIP: '192.168.10.254'

      iplist:
        - # Laser PLC
          internal: '192.168.10.1'
          external: '10.4.42.56'
        - # Auto Gauge PLC
          internal: '192.168.10.100'
          external: '10.4.42.150'

      # prodmon:
      #   collect_config: '10R140 Laser 1725 collect.yml'
      #   post_config: 'post.yml'
      
      laser_db:
        assets: 
          - '1725'

prodmon:
  hosts:
    10R80_Main_BushPress:  # Bushing Press 1513
      ansible_host: '10.4.42.181'
      wanIP: '10.4.42.181'
      lanIP: '192.168.1.251'
      iplist:
        -
          internal: '192.168.1.1' # Main PLC tending 1513
          external: '10.4.43.200'
      prodmon:
        collect_config: '10R80 BushPress 1513 collect.yml'
        post_config: 'post.yml'

    10R80_Uplift_balancer:  # 10R80 Uplift OP30/40/50/60
      ansible_host: '10.4.42.66' 
      wanIP: '10.4.42.66'
      lanIP: '192.168.1.254'
      iplist:
        - 
          internal: '192.168.1.21' # OP 50/60 PLC 1548 1549
          external: '10.4.42.69'
        - 
          internal: '192.168.1.1' # OP 30/40 PLC 1546 1547
          external: '10.4.42.68'
      prodmon:
        collect_config: '10R80 Uplift OP30-40-Bal-Slurry collect.yml'
        post_config: 'post.yml'

    10R80_Uplift_OP70_80:  # OP70 594 / Grind 1551 
      ansible_host: '10.4.42.27'
      wanIP: '10.4.42.27'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.41' # Main PLC
          external: '10.4.42.28'
      prodmon:
        collect_config: '10R80 Uplift OP70 collect.yml'
        post_config: 'post.yml'

    10R80_Uplift_Bush_Press_1552:  # Bushing Press 1552
      ansible_host: '10.4.42.67'
      wanIP: '10.4.42.67'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.10' # Main PLC
          external: '10.4.42.70'
      prodmon:
        collect_config: '10R80 Uplift BushPress collect.yml'
        post_config: 'post.yml'

    10R80_OP100_Main:  # 10R80 Main Bushing Bore 1503
      ansible_host: '10.4.42.182'
      wanIP: '10.4.42.182'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.40' # Main PLC
          external: '10.4.43.100'

    10R80_OP100-110_Main:  # 10R80 Main OP110  Off OP100
      ansible_host: '10.4.43.53'
      wanIP: '10.4.43.53'
      lanIP: '192.168.1.253'
      iplist:
        -
          internal: '192.168.1.50' # Main PLC Tending 1511
          external: '10.4.43.112'
        -
          internal: '192.168.1.170' # Main PLC Tending 1530
          external: '10.4.43.113'
        -
          internal: '192.168.1.58' # OP120 De-elevator
          external: '10.4.43.115'
      prodmon:
        collect_config: '10R80 OP100-110 collect.yml'
        post_config: 'post.yml'

    10R80_OP110_Offline:  # OP110 1528
      ansible_host: '10.4.43.55'
      wanIP: '10.4.43.55'
      lanIP: '192.168.1.251'
      iplist:
        -
          internal: '192.168.1.180' # Main PLC tending 1528
          external: '10.4.43.114'
      prodmon:
        collect_config: '10R80 Offline OP110 collect.yml'
        post_config: 'post.yml'

    10R80_OP110_Uplift:  # machine 1554/751
      ansible_host: '10.4.42.151'
      wanIP: '10.4.42.151'
      lanIP: '192.168.1.253'
      iplist:
        -
          internal: '192.168.1.61' # Main PLC
          external: '10.4.42.152'
        -
          internal: '192.168.1.10' # Nagel Polisher PLC
          external: '10.4.43.30'
      prodmon:
        collect_config: '10R80 Uplift OP100-110 collect.yml'
        post_config: 'post.yml'

    10R80Gauge_1533:  # 10R80 auto gauge 1533
      ansible_host: '10.4.45.101'
      wanIP: '10.4.45.101'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main Cell PLC
          external: '10.4.43.5'
        -
          internal: '192.168.1.61' # Laser 1 PLC 1534
          external: '10.4.43.201'
        -
          internal: '192.168.1.67' # Laser 2 PLC 1505
          external: '10.4.43.202'
      prodmon:
#        collect_config: '10R80 Autogauge 1533 collect.yml'
#        post_config: 'post.yml'
        # new mqtt configs
        collect_config: '10R80 Autogauge 1533 collect.yml'
        post_config: 'post-jemes-mqtt.yml'

    10R60Gauge_1816:  # 10R60 auto gauge 1816
      ansible_host: '10.4.45.107'
      wanIP: '10.4.45.107'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main PLC
          external: '10.4.43.6'
        -
          internal: '192.168.1.10' # Laser Marker PLC 1811
          external: '10.4.42.98'
      prodmon:
        collect_config: '10R60 Autogauge 1816 collect.yml'
        post_config: 'post.yml'

    10R80_1501:
      ansible_host: '10.4.45.104'
      wanIP: '10.4.45.104'
      lanIP: '192.168.1.244'
      iplist:
        -
          internal: '192.168.1.80'  # material handling plc
          external: '10.4.43.110'
      prodmon:
        collect_config: '10R80 Main OP40 Cell2 1501.yml'
        post_config: 'post.yml'

    GFxGauge_1617:
      ansible_host: '10.4.45.106'
      wanIP: '10.4.45.106'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.1'  # main plc
          external: '10.4.43.7'
      prodmon:
        collect_config: 'GFx Autogague 1617 collect.yml'
        post_config: 'post.yml'

    Press240:
      ansible_host: '10.4.45.105'
      wanIP: '10.4.45.105'
      lanIP: '192.168.10.250'
      iplist:
        -
          internal: '192.168.10.10' # Main PLC
          external: '10.4.43.64'
      prodmon:
        collect_config: 'Compact 240 Press collect.yml'
        post_config: 'post.yml'

    Press242:
      ansible_host: '10.4.43.66'
      wanIP: '10.4.43.66'
      lanIP: '192.168.10.250'
      iplist:
          -
            internal: '192.168.10.10' # Main PLC
            external: '10.4.42.238'
          -
            internal: '192.168.10.20' # IOLink Block 1
            external: '10.4.44.200'
          -
            internal: '192.168.10.21' # IOLink Block 2
            external: '10.4.44.201'
          -
            internal: '192.168.10.22' # IOLink Block 3
            external: '10.4.44.202'

      prodmon:
        collect_config: 'Compact 242 Press collect.yml'
        post_config: 'post.yml'

    10R_Assembler:
      ansible_host: '10.4.45.108'
      wanIP: '10.4.45.108'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.1' # Main PLC
          external: '10.4.43.10'
      prodmon:
        collect_config: '10R80 Assembler 1516 collect.yml'
        post_config: 'post.yml'


    Optimized: # Optimized Broach, Inducto & slurry
      ansible_host: '10.4.42.75'
      wanIP: '10.4.42.75'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.1'
          external: '10.4.42.76'
        -
          internal: '192.168.1.24'
          external: '10.4.42.120'
        -
          internal: '192.168.1.26'
          external: '10.4.42.121'
        -
          internal: '192.168.1.28'
          external: '10.4.42.122'

      prodmon:
        collect_config: 'Optimised Slury Inducto collect.yml'
        post_config: 'post.yml'

    TrilobeSlurry: # Trilobe Slurry 742
      ansible_host: '10.4.45.109'
      wanIP: '10.4.45.109'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.1'
          external: '10.4.43.220'

      prodmon:
        collect_config: 'Trilob Slurry 742 collect.yml'
        post_config: 'post-jemes-mqtt.yml'
        

    AB1VLaser1750:
      ansible_host: '10.4.42.60'
      wanIP: '10.4.42.60'
      lanIP: '192.168.1.254'
      # laser_db: true
      iplist:
        - # Automation PLC
          internal: '192.168.1.3'
          external: '10.4.42.45'
      prodmon:
        collect_config: 'AB1V Laser 1750 collect.yml'
        post_config: 'post.yml'

    Laser1724:
      ansible_host: '10.4.42.53'
      wanIP: '10.4.42.53'
      lanIP: '192.168.10.254'
      # laser_db: true
      iplist:
        - # Automation PLC
          internal: '192.168.10.1'
          external: '10.4.42.54'
      prodmon:
        collect_config: 'AB1V Rx Laser 1724 collect.yml'
        post_config: 'post.yml'

    Laser1725:
      ansible_host: '10.4.42.55'
      wanIP: '10.4.42.55'
      lanIP: '192.168.10.254'
      # laser_db: true
      iplist:
        - # Automation PLC
          internal: '192.168.10.1'
          external: '10.4.42.56'
        - # Auto Gauge PLC
          internal: '192.168.10.100'
          external: '10.4.42.150'
      prodmon:
        collect_config: '10R140 Laser 1725 collect.yml'
        post_config: 'post.yml'

    TrilobeAssembler:
      ansible_host: '10.4.45.107'
      wanIP: '10.4.45.107'
      lanIP: '192.168.1.254'
      # laser_db: true
      # iplist:
      #   - # Automation PLC
      #     internal: '192.168.10.1'
      #     external: '10.4.42.56'
      #   - # Auto Gauge PLC
      #     internal: '192.168.10.100'
      #     external: '10.4.42.150'
      prodmon:
        collect_config: 'TrilobeAssemblercollect.yml'
        post_config: 'post.yml'




  vars:
      ansible_ssh_user: pi
      ansible_ssh_pass: pi
      ansible_become_user: root
      ansible_become_password: pi

