ungrouped:
  hosts:

prodmon:
  hosts:
    10R80Gauge_1533:  # 10R80 auto gauge 1533
      ansible_host: '10.4.45.101'
      wanIP: '10.4.45.101'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main Cell PLC
          external: '10.4.43.5'
        -
          internal: '192.168.1.61' # Laser 1 PLC 1534
          external: '10.4.43.201'
        -
          internal: '192.168.1.67' # Laser 2 PLC 1505
          external: '10.4.43.202'

      prodmon:
        collect_config: '10R80 Autogauge 1533 collect.yml'
        post_config: 'post.yml'

    10R60Gauge_1816:  # 10R60 auto gauge 1816
      ansible_host: '10.4.45.107'
      wanIP: '10.4.45.107'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main PLC
          external: '10.4.43.6'
        -
          internal: '192.168.1.10' # Laser Marker PLC 1811
          external: '10.4.42.98'

      prodmon:
        collect_config: '10R60 Autogauge 1816 collect.yml'
        post_config: 'post.yml'

    new108:  # 
      ansible_host: '10.4.45.108'
      wanIP: '10.4.45.108'
      lanIP: '192.168.1.250'
      iplist:
        -
          internal: '192.168.1.2' # Main PLC
          external: '10.4.43.6'

      # prodmon:
      #   collect_config: ' collect.yml'
      #   post_config: 'post.yml'

    10R140Laser_1725:  # 
      ansible_host: '10.4.45.108'
      wanIP: '10.4.44.108'
      lanIP: '192.168.10.254'

      iplist:
        - # Laser PLC
          internal: '192.168.10.1'
          external: '10.4.42.56'
        - # Auto Gauge PLC
          internal: '192.168.10.100'
          external: '10.4.42.150'

      # prodmon:
      #   collect_config: '10R140 Laser 1725 collect.yml'
      #   post_config: 'post.yml'
      
      laser_db:
        assets: 
          - '1725'


    10R80_1501:
      ansible_host: '10.4.45.104'
      wanIP: '10.4.45.104'
      lanIP: '192.168.1.244'
      iplist:
        -
          internal: '192.168.1.80'  # material handling plc
          external: '10.4.43.110'
      
      prodmon:
        collect_config: '10R80 Main OP40 Cell2 1501.yml'
        post_config: 'post.yml'


    GFxGauge_1617:
      ansible_host: '10.4.45.106'
      wanIP: '10.4.45.106'
      lanIP: '192.168.1.254'
      iplist:
        -
          internal: '192.168.1.1'  # main plc
          external: '10.4.43.7'
      
      prodmon:
        collect_config: 'GFx Autogague 1617 collect.yml'
        post_config: 'post.yml'


    Press240:
      ansible_host: '10.4.45.105'
      wanIP: '10.4.45.105'
      lanIP: '192.168.10.250'
      iplist:
        -
          internal: '192.168.10.10' # Main PLC
          external: '10.4.43.64'

      # prodmon:
      #   collect_config: 'Press 240 collect.yml'
      #   post_config: 'post.yml'

  vars:
      ansible_ssh_user: pi
      ansible_ssh_pass: pi
      ansible_become_user: root
      ansible_become_password: pi

