---
# handlers file for config_stackpole_networking_role

- name: saveiptables
  shell: iptables-save > /etc/iptables/rules.v4

# this must run last: a new setup changes the ip address of the wan interface
- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted
